### PR TITLE
Merged dhewm 1.5.2.

### PR DESCRIPTION
**Pull request by isojalka**
Huge diff, sorry about that :)

This should merge the dhewm 1.5.2 release more or less cleanly, making it easier to stay up-to-date with upstream changes in the future, and to inspect the differences in this fork compared to the upstream release.

### CODE REVIEW

**Comment by Cowcat5150** [comment]
Yep. Huge :)

Got to check out the changes and see what's going on here: Not that I did
not upgrade some of the code before but some issues raised for MorphOS
while doing it ( sound, event code, etc ).

But well, If you did this job ( you compiled it and all is working )
.....May I suspect that is related to the TinyGL schedule development ? :)

**Comment by isojalka** [comment]
My testing so far is limited to starting the game and running around on the first level for a bit :D But as far as I can tell, everything is working as normal. Of course please do try it out yourself too, and if you run into any problems, let me know and I'll fix it!

And yes, this is of course related to the TinyGL development :)

**Comment by Cowcat5150** [comment]
I'm on it.
Ironically, all the "debugger tool" upgrades for dhewm3 have no use for
versions other than Windows AFAIK. And I have a version that bypassed all
of it (less crap).

Thanks for your interest.

As a side note I couldn't collaborate to the tinygl bounty fast enough:
Being unemployed most of the time doesn't help.

**Comment by isojalka** [comment]
> Ironically, all the "debugger tool" upgrades for dhewm3 have no use for
> versions other than Windows AFAIK. And I have a version that bypassed all
> of it (less crap).

And no use for people who just want to play the game, I'm sure. Nonetheless, it's part of Dhewm3, and not merging it now just makes merging future versions more difficult.

> As a side note I couldn't collaborate to the tinygl bounty fast enough:
> Being unemployed most of the time doesn't help.

Definitely don't worry about that! It's 100% voluntary, and you definitely shouldn't do it if you're in a tight spot yourself! I and everyone else are already happy with all the work you've put into this port! :)

**Pull request merged**
